--- 
title: "Building a Transferable Omics Prediction (TOP) Model"
author: Harry Robertson, Nicholas Robertson <br>
date: "2023-24-01"
output: 
    BiocStyle::html_document:
    css: style.css
    toc: true
vignette:
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteIndexEntry{Building a Transferable Omics Prediction (TOP) Model}

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installing the TOP package
Installing the TOP package from github can be achieved using the following command 
```{r, eval=FALSE}
devtools::install_github("Harry25R/TOP", dependencies = TRUE)
```

## Loading the required packages
```{r}
library(TOP)
library(ggplot2)
library(dplyr)
library(curatedOvarianData)

theme_set(theme_bw())
```

## Loading in the example data
The example data used in this vignette is the curatedOvarianData. Described in the paper from [Benjamin Frederick Ganzfried et al (2013)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3625954/) \n
```{r}
data(package = "curatedOvarianData")


```

